name: CI

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    uses: dvsa/.github/.github/workflows/php-library-security.yml@main
    with:
      php-versions: "[\"8.2\", \"8.3\"]"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  static-analysis:
    uses: dvsa/.github/.github/workflows/php-library-static.yml@main
    with:
      php-version: '8.3'
      stability: '["prefer-stable"]'

  tests:
    uses: dvsa/.github/.github/workflows/php-library-tests.yml@main
    with:
      php-versions: "[\"8.2\", \"8.3\"]"
      fail-fast: false
